name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main  # Se a sua branch principal for 'master', mude aqui para 'master'

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Baixa o código do seu repositório
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Configura o ambiente Java (necessário para o Flutter)
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # 3. Instala e configura a versão do Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      # 4. Baixa as dependências do pubspec.yaml
      - name: Get Dependencies
        run: flutter pub get

      # 5. Compila o projeto para Web em modo Release
      - name: Build Web
        run: flutter build web --release --base-href "/${{ github.event.repository.name }}/"

      # 6. Faz o deploy dos arquivos gerados na branch gh-pages
      - name: Deploy to GitHub Pages
        uses: PeaceIris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web